= hudson and Serena Dimensions : easy integration
:published_at: 2009-06-27
:hp-tags: continuous integration, hudson, SCM

Though there is a Hudson plugin for PVCS, there's none for Serena Dimensions. I searched how to use Hudson and Dimensions together but didn't find a,ything on Internet. So here's the solution I use.

Fortunaltely, there's a quick and easy way to add a project in Hudson with source control under Dimensions. Just add a step to the build with shell script or Windows batch command and use the Dimensions command line `dmcli` :

[source,xml]

-----------------------
 dmcli -user <user> -pass
<pass> -host <host:port> -dbname <dbname> -dsn <SID> download /WORKSET=CATAL:WS_PHONEBOOK /DIRECTORY=Phonebook 
-----------------------

You should be able to use the option -file also (which i didn't try) : see http://community.serena.com/posts/54287b495d[this post on Serena forum] for more information.

To get more help on dmcli option, just call dmcli without command and use help to get more information on internal commands. The cons of this is that you won't have changes informations in the hudson change log :(.

On Windows, if you use Hudson as a service, the dmcli command won't work directly : I suppose you must update the path before calling dmcli (or enter the full path to the command, but didn't check it.
