= Cross-Origin Resource Sharing with Play! framework
:published_at: 2011-12-04
:hp-tags: CORS, Cross-Origin Resource Sharing, playframework

I was trying to develop with play! framework for a 3-tier achitecture. So I run 2 applications on the same machine but on 2 differents ports (the front on 9010 and the back application on 9011 that has access to the database).

Trying to call WS services (with JSON format) from the front controllers is transparent.

[code language="java"]

public static void index() \{

HttpResponse response = WS.url("http://localhost:9011/api/accounts").get();

JsonElement json = response.getJson();

render(json);

}

[/code]

But trying to make dynamic pages with JQuery querying from the front page the the back controller, the results were blocked due tothe http://en.wikipedia.org/wiki/Same_origin_policy[Same Origin Policy]. So I had to specify the http://en.wikipedia.org/wiki/Cross-Origin_Resource_Sharing[Cross-Origin Resource Sharing] on the back controller.

Here is the code to add on the controller of the backapplication : this will add the header to allow the caller to access the service :

[code language="java"]

public static void listAccounts() \{

List<Account> accounts = Account.findAll();

Http.Header hd = new Http.Header();

hd.name = "Access-Control-Allow-Origin";

hd.values = new ArrayList<String>();

hd.values.add("http://localhost:9010");

Http.Response.current().headers.put("Access-Control-Allow-Origin",hd);

renderJSON(accounts);

}

[/code]

You can sepecify a list of domains to accept as origin, or set it to _*_ to allow all domains to call your service.

And the JQuery call :

[code language="javascript"]

$("#accounts").click(function()\{

$.getJSON('http://localhost:9011/api/accounts', function(accounts) \{

var items = [];

$.each(accounts, function(title, acc) \{

console.log(acc);

$("#results").append('<p>'+acc.number+'</p>');

});

});

});

[/code]

You can generalize the CORS setting with the @Before annotation, so all your services in a class will be accessible :

[code language="language="]

@Before

public static void setCORS() \{

Http.Header hd = new Http.Header();

hd.name = "Access-Control-Allow-Origin";

hd.values = new ArrayList<String>();

hd.values.add("http://localhost:9010");

Http.Response.current().headers.put("Access-Control-Allow-Origin",hd);

}

[/code]

Then your services coding in the controller is wery simple :

[code language="java"]

public static void listAccounts() \{

List<Account> accounts = Account.findAll();

renderJSON(accounts);

}

[/code]
